#!/bin/bash

# luavm-install - Install luavm

Program='luavm'
Rawrepo='https://gitlab.com/pepa65/luavm/raw/master'
Src="$HOME/.luavm/src"  # Source code dir

Print(){ echo -e "\033[1m  $1\033[0m";}

Install(){
	mkdir -p "$Src"
	Print "Downloading $Program..."
	cd "$Bin"
	[[ -e $Program ]] && Print "Removing existing $Program..." && rm "$Program"
	wget "$Rawrepo/$Program"
	chmod 775 "$Program"

	# Add luavm to path
	local str="export PATH=\"$Bin:\$PATH\"" shell=$(basename $SHELL) profile=
	Print "Detected shell: $shell"
	[[ $shell = bash && -f $HOME/.bashrc ]] && profile="$HOME/.bashrc"
	[[ $shell = zsh && -f $HOME/.zshrc ]] && profile="$HOME/.zshrc"
	[[ -z $profile ]] &&
		Print "'$Bin' needs to be added to PATH."
		Print "No profiles found (~/.bashrc or ~/.zshrc) to modify..." &&
		Print "This line needs to be added manually to the right file:" &&
		Print "  $str"
	[[ $profile ]] && ! grep -q "$str" "$profile" &&
		Print "Appending '$str' at the end of $profile" &&
		echo -e "\n$str" >>"$profile" &&
		Print "Start a new terminal or run:\nsource $profile"
}

Print "Installing $Program"
Install
Print "Install successful"
